project_id = "tkgwflnzhuqfywasreea"

[functions.grok-confirm]
verify_jwt = false

[functions.mint-nft]
verify_jwt = false

[functions.get-carv-price]
verify_jwt = false

[functions.verify-prediction]
verify_jwt = false

[functions.check-predictions]
verify_jwt = false

[functions.initialize-user]
verify_jwt = false